config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pricing', to: 'pages#pricing'
  get 'contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :pricing, :contact]

  def home
  end

  def pricing
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="wrapper">
  <div class="container-contact bg-blue">
    <div class="row">
      <div class="col xs-10 xs-2-offset">
        <div class="address text-center">
          <h2>Où nous trouver et nous contacter ?</h2>
          <div class="contact">
            <div class="col-xs-12 col-sm-4 col-md-4">
              <h3> Où sommes-nous ? </h3>
              <h4><i class="fa fa-location-arrow" aria-hidden="true"></i> 22 rue Victor Hugo</h4>
              <h4>78370 - PLAISIR</h4>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
              <h3> Nous joindre </h3>
              <h4><i class="fa fa-phone" aria-hidden="true"></i> +33 6 34 56 75 76</h4>
              <h4><i class="fa fa-envelope" aria-hidden="true"></i> contact@nomadhome.fr</h4>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
              <h3> Comment y aller ? </h3>
              <h4><i class="fa fa-train" aria-hidden="true"></i> Gare Montparnasse : Ligne N</h4>
              <h4><i class="fa fa-car" aria-hidden="true"></i> 35 minutes de voiture de Paris </h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/map' %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/240223/pexels-photo-240223.jpeg');">

  <div class="container">
    <div class="row">
      <div class="col-xs-6 appearIn">
        <h1>NomadHome</h1>
        <br>
        <p>Un lieu de travail où vous êtes à la maison.</p>
        <p>Faites de chaque jour une aventure.</p>
        <br>
        <a href="" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#orderForm">PLUS D'INFOS</a>
      </div>
      <div class="col-xs-6"></div>
    </div>
  </div>
  <div class="text-center" style="position: relative; top: 110px;">
    <a href="#features">
      <i class="fa fa-angle-down pulse" style="font-size: 50px; color: white;"></i>
    </a>
  </div>

</div>

<div class="bg-blue" id="features">
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="card" data-sr="wait 0.5s, ease-in-out 100px">
          <%= image_tag "24.svg" %>
          <h2>Ouvert 24h/24</h2>
          <p>Un des seuls espaces de coworking à être ouvert <strong>toute l'année quand vous le souhaitez. Du jamais vu.</strong></p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="card" data-sr="wait 0.5s, ease-in-out 100px">
          <%= image_tag "yoga.svg" %>
          <h2>Concentration</h2>
          <p>Situé près de la forêt dans un <strong>cadre tranquille </strong>. Un contexte parfait pour travailler dans le calme absolu</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="card" data-sr="wait 0.5s, ease-in-out 100px">
          <%= image_tag "coffee.svg" %>
          <h2>Lieu de vie</h2>
          <p>Avec une cuisine dédiée et quelques installations pour décompresser, NomadHome est aussi un <strong>endroit de partage</strong></p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="card" data-sr="wait 0.5s, ease-in-out 100px">
          <%= image_tag "network.svg" %>
          <h2>Collaboration</h2>
          <p>L'opportunité de <strong>travailler avec des talents</strong> qui se complètent à travers leurs expériences et compétences</p>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center" style="position: relative; top: 30px;">
    <a href="#newsletter">
      <i class="fa fa-angle-down pulse" style="font-size: 50px; color: white;"></i>
    </a>
  </div>
</div>

<div class="text-center padded" id="newsletter">
  <h2>Des nouvelles de NomadHome ?</h2>
  <p>Laissez votre email et vous aurez les dernières news :</p>
  <form class="form-inline">
    <input type="email" placeholder="bob@gmail.com" class="form-control">
    <input type="submit" value="Souscrire" class="btn btn-primary">
  </form>
</div>


<script>
    window.sr = new ScrollReveal()
		sr.reveal('.card', { origin: 'left', distance: '20px', duration: 3000, })
</script>

<!-- Modal -->
<div class="modal fade" id="orderForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Réservez votre spot</h4>
      </div>
      <div class="modal-body">
        <form action="">

          <div class="row">
            <div class="col-xs-6">
              <div class="form-group">
                <label for="firstname">Prénom</label>
                <input type="text" placeholder="Bob" class="form-control" id="firstname">
              </div>
            </div>
            <div class="col-xs-6">
              <div class="form-group">
                <label for="lastname">Nom</label>
                <input type="text" placeholder="L'éponge" class="form-control" id="lastname">
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" placeholder="bob@gmail.com" id="email">
          </div>
          <div class="form-group">
            <label for="exampleSelect1">Sélectionner un pack :</label>
            <select class="form-control" id="exampleSelect1">
              <option>Nomade</option>
              <option>Bird</option>
              <option>Home</option>
            </select>
          </div>
          <input type="submit" value="Réserver" class="btn btn-primary">
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
        <button type="button" class="btn btn-primary">Sauvegarder</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/pricing.html.erb
<div class="wrapper">
  <div class="container-contact bg-blue">
    <div class="row">
      <div class="col xs-10 xs-2-offset">
        <div class="pricing text-center">
          <h2>Une expérience de travail unique</h2>
          <p>Plusieurs formules et options vous sont proposées, que vous vouliez être nomade ou résident.</p>
          
          <div class="price">
            <div class="col-xs-12 col-sm-4">
              <div class="offer bg-yellow">
                <h3>Nomade </h3>
                <h4>Sans engament</h4>
                <h4>3€/heure - 15€/jour</h4>
              </div>
              <div class="suboffer">
                <ul>
                  <li>Evènements membres </li>
                  <li>Café</li>
                  <li>Wifi</li>
                </ul>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4">
              <div class="offer bg-orange">
                <h3>Bird </h3>
                <h4>Sans engament</h4>
                <h4>100€/mois</h4>
              </div>
              <div class="suboffer">
                <ul>
                  <li>Réseau Slack</li>
                  <li>Invité : 10€/jour</li>
                  <li>Imprimante</li>
                </ul>
              </div>
            </div>
            <div class="col-xs-12 col-sm-4">
              <div class="offer bg-red">
                <h3>Home </h3>
                <h4>Avec engagement</h4>
                <h4>300€/mois</h4>
              </div>
              <div class="suboffer">
                <ul>
                  <li>Bureau dédié</li>
                  <li>Casier</li>
                  <li>Salle de réunion</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/7097/people-coffee-tea-meeting.jpg');"></div>

<script>
    window.sr = new ScrollReveal()
		sr.reveal('.offer', { origin: 'top', distance: '30px', duration: 3000, })
    sr.reveal('.suboffer', { origin: 'bottom', distance: '30px', duration: 3000, })
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-xs-4">
          <ul class="list-inline">
            <li><a href=""><i class="fa fa-youtube"></i></a></li>
            <li><a href=""><i class="fa fa-instagram"></i></a></li>
            <li><a href=""><i class="fa fa-facebook"></i></a></li>
            <li><a href=""><i class="fa fa-twitter"></i></a></li>
          </ul>
        </div>
        <div class="col-xs-8 text-right">
          <p>@NomadHome</p>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_map.html.erb
<div class="container">

<div id="map" style="width: 100%; height: 400px;"></div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<script type="text/javascript">
var myLatlng = new google.maps.LatLng(48.8184947,1.9182630999999901);

var myOptions = {
  zoom: 10,
  center: myLatlng,
  scrollwheel: false,
  mapTypeId: google.maps.MapTypeId.ROADMAP,
  styles: [
    {
        "featureType": "landscape.man_made",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#f7f1df"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#d0e3b4"
            }
        ]
    },
    {
        "featureType": "landscape.natural.terrain",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.business",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.medical",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#fbd3da"
            }
        ]
    },
    {
        "featureType": "poi.park",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#bde6ab"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffe15f"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#efd151"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "black"
            }
        ]
    },
    {
        "featureType": "transit.station.airport",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#cfb2db"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#a2daf2"
            }
        ]
    }
]
};

var map = new google.maps.Map(document.getElementById('map'), myOptions);
var marker = new google.maps.Marker({
  position: myLatlng,
  map: map,
  title:"You are here!"
});
</script>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-wagon" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag 'logo.svg' %>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to pricing_path do %>
                <i class="fa fa-euro"></i> Tarifs
                <% end %>
            </li>
            <li>
              <%= link_to contact_path do %>
                <i class="fa fa-envelope-o"></i> Contact
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Suivez-nous <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="https://www.facebook.com/lewagonformation"><i class="fa fa-facebook-square"></i> Facebook</a></li>
                <li><a href="https://twitter.com/lewagonparis"><i class="fa fa-twitter-square"></i> Twitter</a></li>
              </ul>
            </li>
            <li><a href="#" data-toggle="modal" data-target="#orderForm" class="btn">Réserver un spot</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>